name: test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract
        uses: ./actions.yml
        with:
          packages: |
            btop
            jq

      - name: Test
        run: |
          echo "{ \"name\": \"test\" }" > test.json
          jq -r '.name' test.json
          which btop
